dist: trusty
sudo: true

matrix:
  include:
    - os: osx
    - os: linux

language: csharp
mono: none
dotnet: 2.1.300

install:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install mono-libgdiplus libpng; fi

- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository ppa:quamotion/ppa; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y libgdiplus libpng-dev; fi

script:
- dotnet --version
- dotnet restore
- dotnet build -c Release
- cd Benchmarks
- dotnet run -c Release
