dist: trusty
sudo: false

matrix:
  include:
    - os: osx
    - os: linux

language: csharp
mono: none
dotnet: 2.1.300

script:
- dotnet --version
- dotnet restore
- dotnet build -c Release
- cd Benchmarks
- dotnet run -c Release
